#!/bin/zsh
# Functions

sl() { du -a ~/Documents/2lycee/* | awk '{print$2}' | grep -e ".md" -e ".txt" -e ".tex" -e ".html" | fzf -m | xargs -r $EDITOR ;}
sp() { find ~/Documents/2lycee/* ~/Downloads/* -name "*.pdf" -print | fzf -m | xargs -r zathura ;}
sep() { find -name "*.pdf" -print | fzf -m | xargs -r zathura ;}
seb() {  ebook-viewer $(find ~/Documents/* ~/manpages/bman/* -name "*.epub" -print | fzf -m) ;}
# Copy to desired directory
cl() {  mv -vi "$1"  -t $(find ~/Documents/2lycee/ -type d | fzf --prompt='Dest> ')  ;}
update_package_list(){
    apt-mark showmanual > ~/Documents/install-scripts/manual-packages.txt
}
# Search man pages
fman() {
    man $(apropos --long . | fzf --prompt='Man> ' | awk '{print $1}')
}
fca() {
    caja $(find ~ -type d | fzf -m --prompt='Dirs>')
}
urls() {
    echo "$1" >> $HOME/.config/newsboat/urls
}

def() {
    dict -d gcide "$1" | less
}
deffs() {
    dict -d fd-fra-spa "$1"
}
defse() {
    dict -d fd-spa-eng "$1"
}
cpl() {
    rclone copy "$1" remotebak: -P
}
rpl() {
    rclone copy remotebak:"$1" . -P
}
nv() {
    du -a ~/vimwiki/* | awk '{print$2}' | fzf | xargs -r $EDITOR ;
}
cfg() {
    find ~/.config -type f -print | fzf | xargs -r $EDITOR ;
}
homepage() {
    $EDITOR ~/Documents/config/homepage.html ~/Documents/config/homepage.css
}
show() {
    aptitude search -F '%p' '.*' | fzf --height 100 -m --preview 'cat <(aptitude show {1} | par w 50)'
}

