#!/bin/zsh
# Functions

sl() { du -a ~/Documents/2lycee/* | awk '{print$2}' | grep -e ".md" -e ".txt" -e ".tex" -e ".html" | fzf | xargs -r $EDITOR ;}
sp() { du -a ~/Documents/2lycee/* ~/Downloads/* | awk '{print$2}' | grep .pdf | fzf | xargs -r zathura ;}
seb() { du -a ~/Documents/* ~/manpages/bman/* | awk '{print$2}' | grep -e '.epub' | fzf | xargs -r ebook-viewer ;}
# Copy to desired directory
cl() { find ~/Documents/2lycee/ -type d | fzf --prompt='Dest> ' | xargs -r mv -vi "$1"  "$2"  "$3" "$4" -t ;}

vf() { fzf | xargs -r -I % $EDITOR % ;}
fman() {
    man -k . | fzf --prompt='Man> ' | awk '{print $1}' | xargs -r man
}
# fd - cd to selected directory
fdi() {
  local dir
  dir=$(find ${1:-.} -path '*/\.*' -prune \
                  -o -type d -print 2> /dev/null | fzf +m) &&
  cd "$dir" }
update_package_list(){
    apt-mark showmanual > ~/Documents/install-scripts/manual-packages.txt
}
# Search man pages
fman() {
    apropos --long . | fzf --prompt='Man> ' | awk '{print $1}' | xargs -r man
}
#dman() {
#    man "$(apropos --long "$1" | dmenu -i -l 10 | awk '{print $2, $1}' | tr -d '()')"
#}
urls() {
    echo "$1" >> $HOME/.config/newsboat/urls
}


def() {
dict -d gcide "$1" | less
}
# testman() {
#     man -k "$1" | fzf | awk '{print $1}' | xargs -r man -w | xargs -r ./.mancolor
# }
cpl() {
    rclone copy "$1" pcloudbak: 
}
rpl() {
    rclone copy pcloudbak:"$1" .
}
